# Generated by Django 5.0 on 2024-01-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.CharField(default='...', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AbstractUsername', models.TextField(default='...', help_text='Введите своё Имя и Фамилию. Например: Иван Иванов')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_or_news', models.CharField(choices=[('NEWS', 'новость'), ('POST', 'статья')], default='NEWS', max_length=4)),
                ('date_time_creation_post', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='...', max_length=255)),
                ('text', models.TextField(default='...')),
                ('rating', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='...', max_length=255)),
                ('date_time_creation_comment', models.DateTimeField(auto_now_add=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('AbstractUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.AbstractUser')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='AbstractUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.AbstractUser'),
        ),
    ]
