# Generated by Django 5.0 on 2023-12-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_user_author_name_alter_author_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(default='...', help_text='Введите своё Имя и Фамилию. Например: Иван Иванов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='...', help_text='Введите своё Имя и Фамилию. Например: Иван Иванов'),
        ),
    ]
