# Generated by Django 5.0 on 2023-12-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_name_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='news_rating',
            new_name='rating',
        ),
    ]
