# Generated by Django 5.0 on 2023-12-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_comment_rating_comment_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
