# Generated by Django 5.0 on 2024-02-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractuser',
            old_name='AbstractUsername',
            new_name='username',
        ),
    ]
