# Generated by Django 5.0 on 2023-12-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_user_rating_author_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
